import {StyleSheet} from 'react-native';
import Colors from './Colors';

export default StyleSheet.create({
  bold30: {
    fontFamily: 'Inter-Regular',
    fontWeight: 'bold',
    fontSize: 30,
    flexWrap: 'wrap',
  },
  bold30White: {
    fontWeight: 'bold',
    fontSize: 30,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold26: {
    fontWeight: 'bold',
    fontSize: 26,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold24White: {
    fontWeight: 'bold',
    fontSize: 24,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
    color: Colors.WHITE,
  },
  normal21: {
    fontSize: 21,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold21: {
    fontWeight: 'bold',
    fontSize: 21,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
    color: Colors.BLACK,
  },
  bold20White: {
    fontWeight: 'bold',
    fontSize: 20,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold20: {
    fontWeight: 'bold',
    fontSize: 20,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
    color: Colors.BLACK,
  },
  normal18: {
    fontSize: 18,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold17: {
    fontWeight: 'bold',
    fontSize: 17,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold17White: {
    fontWeight: 'bold',
    fontSize: 17,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold16: {
    fontWeight: 'bold',
    fontSize: 16,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold16White: {
    fontWeight: 'bold',
    fontSize: 16,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold15: {
    fontWeight: 'bold',
    fontSize: 15,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold14White: {
    fontWeight: 'bold',
    fontSize: 14,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  normal15: {
    fontSize: 15,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  normal14: {
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  normal14White: {
    fontSize: 14,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
    color: Colors.WHITE,
  },
  normal13: {
    fontSize: 13,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
    color: Colors.BLACK,
  },
  bold13: {
    fontWeight: 'bold',
    fontSize: 13,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
    color: Colors.BLACK,
  },
  bold13White: {
    fontWeight: 'bold',
    fontSize: 13,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  bold12White: {
    fontWeight: 'bold',
    fontSize: 12,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  normal12: {
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  normal12White: {
    fontSize: 12,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  h4: {
    fontSize: 20,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  h5: {
    fontSize: 18,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  h6: {
    fontSize: 18,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  body: {
    fontSize: 16,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
  buttonTitleText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: Colors.WHITE,
    fontFamily: 'Inter-Regular',
    flexWrap: 'wrap',
  },
});
